In [1]:
#user

In [1]:
import base

In [2]:
from dataset.sig_dataset import SigDataModule

In [3]:
from model.sig_model import CVAE,MLP

In [4]:
import torch.nn as nn
import torch

In [5]:
from utils.leadlag import leadlag
from utils import tosig
import logsig_inversion

In [6]:
import numpy as np

In [7]:
def get_net(model_path=''):
    input_dim = 8
    condition_dim = 8
    batch = 32

    middle_dim = 50
    hidden_dim = 8
    common_network = nn.Sequential(
        MLP([input_dim + condition_dim,middle_dim])
    )
    mean_network = nn.Sequential(
        MLP([middle_dim,hidden_dim],last_activation=False)
    )
    logvar_network = nn.Sequential(
        MLP([middle_dim,hidden_dim],last_activation=False)
    )
    decode_network = nn.Sequential(
        MLP([hidden_dim+condition_dim,input_dim],last_activation=False),
        nn.Sigmoid(),
    )
    net = CVAE.load_from_checkpoint(model_path,common_network = common_network, 
                                mean_network=mean_network, 
                                logvar_network= logvar_network,
                                decode_network = decode_network,
                                optim=torch.optim.Adam,lr=0.001)
    return net

In [16]:
EURUSD_path = 'test_30.ckpt'
net = get_net(EURUSD_path)

INFO:root:struct init
INFO:root:encoder_init_over
INFO:root:decoder_init_over
INFO:root:optim_init_over
INFO:root:struct init_over


In [25]:
def concatenate(net,condition,level=4):#periods 期 一单元是一个月 所以3期就是 3*1 = 3个月
    generated = net.generate(condition)
    generated = dm.minmax.inverse_transform(generated.detach().numpy())
    sig, order, n_iterations, n_organisms, n_points, pip, n_pips,
    path, loss = logsig_inversion.train(generated, level=4, n_iterations=100, n_organisms=100, n_points=21,#window
                                        pip=0.01, n_pip=50*100)
    return path

In [26]:
def generate_data(price,condition,batch_size,data_type='EURUSD_30'):

    if data_type =='EURUSD_30':
        EURUSD_path = 'test_30.ckpt'
        net = get_net(EURUSD_path)

    paths = [concatenate(net,condition, 1) for _ in range(batch_size)]# 条数 生成几条数据
    generated = price + np.transpose(paths)
    return gener_paths

In [27]:
import os
dm = SigDataModule(path=os.path.join(base.data_path,'SP 500 GSPC.csv'),batch_size=32,level=4)
dm.prepare_data()

In [35]:

idx = 195
condition = dm.conditions[idx]
price = dm.windows[idx + 1][0, 0]

In [29]:
generated = generate_data(price,condition,batch_size=10)

INFO:root:struct init
INFO:root:encoder_init_over
INFO:root:decoder_init_over
INFO:root:optim_init_over
INFO:root:struct init_over


TypeError: train() got an unexpected keyword argument 'level'

In [14]:
import matplotlib.pyplot as plt
plt.plot(generated)
plt.xlabel("Days", fontsize=14) 
plt.show()#

NameError: name 'generated' is not defined

In [17]:
test.logsigs.shape

(1109, 8)

In [18]:
test.conditions.shape

(1109, 8)

In [18]:
import pandas as pd

In [23]:
aa = pd.read_csv(os.path.join(base.data_path,'SP 500 GSPC.csv'))

In [40]:
list1 = [i[:7] for i in aa.Date.tolist()]
res = []
[res.append(i) for i in list1 if i not in res]
1

1

In [44]:
dic = {res[:-1][i]:(test.conditions[i],test.logsigs[i]) for i in range(1109)}

In [45]:
dic

{'1927-12': (array([0.53361688, 0.53361688, 0.99999   , 0.04119649, 0.02303391,
         0.99993142, 0.99902501, 0.99744245]),
  array([0.53341637, 0.53341637, 0.99998929, 0.04119649, 0.02303391,
         0.99993142, 0.99902501, 0.99744245])),
 '1928-01': (array([0.53341637, 0.53341637, 0.99998929, 0.04119649, 0.02303391,
         0.99993142, 0.99902501, 0.99744245]),
  array([0.53333195, 0.53333195, 0.99998952, 0.04119649, 0.02303391,
         0.99993142, 0.99902501, 0.99744245])),
 '1928-02': (array([0.53333195, 0.53333195, 0.99998952, 0.04119649, 0.02303391,
         0.99993142, 0.99902501, 0.99744245]),
  array([0.5357064 , 0.5357064 , 0.99998891, 0.04119649, 0.02303391,
         0.99993142, 0.99902501, 0.99744245])),
 '1928-03': (array([0.5357064 , 0.5357064 , 0.99998891, 0.04119649, 0.02303391,
         0.99993142, 0.99902501, 0.99744245]),
  array([0.53450334, 0.53450334, 0.99998885, 0.04119649, 0.02303391,
         0.99993142, 0.99902501, 0.99744245])),
 '1928-04': (array([0.53